name: music_led_2_0_app
description: App Flutter para controlar tira LED vía Bluetooth
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  provider: ^6.0.0
  # Agrega otras dependencias necesarias

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
